services:
  db:
    image: postgres:15
    container_name: alma_db
    restart: always
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_db
    ports:
      - "440:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    container_name: alma_redis
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data

  api:
    build: .
    container_name: alma_api
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://my_user:root@db:5432/my_db
      JWT_SECRET: change_me_secret_key
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./static/uploads:/app/static/uploads

volumes:
  pg_data:
  redis_data:

